### ISSUE TITLE
empty output for heapsort.py

### ISSUE THREAD

**Issue by tankf33der** [GordonCharlton/Quackery#10]
is empty output is ok ?

```
$ python3.11 quackery.py sundry/heapsort.qky 

$
```

**Comment by GordonCharlton** [comment]
Yes, that's exactly what I would expect. 

The file `heapsort.qky` extends the Quackery word dictionary so that it can do a heapsort, but does not do anything that prints to the terminal. 

Try adding these two lines to the end of `heapsort.qky`

```
  words
  ' [ 1 3 2 4 6 5 8 7 9 ] hsort cr echo

```

`words` will cause Quackery to display the words it knows about, so you can confirm that it now includes the words defined in `heapsort.qky`, namely `pq pq.peek pq.poke parent has-parent child has-child sibling has-sibling comparison pq.compare toheap pq.heapify fromheap makeheap hsortwith` and `hsort`.

` ' [ 1 3 2 4 6 5 8 7 9 ] hsort cr echo` will illustrate that the heapsort works - it should display `[ 1 2 3 4 5 6 7 8 9 ]`.

Hope this helps. :-)
