### ISSUE TITLE
`protect` causes `bailed` to mess up `history`

### ISSUE THREAD

**Issue by olus2000** [GordonCharlton/Quackery#3]
When working on a Quackery extension to solve #1 I needed to create a new protected ancillary stack. Trying to load this extension resulted in an unhelpful problem report:
```Quackery
       Problem: Cannot remove an immovable item.
Quackery Stack: [ file.path share [ ' [ ... ... ... ... ... ... ... ... ... ... ... ] ] join file.path put ' [ [ ... ... ] [ ... ... ] [ ... ... ] ] witheach [ do loadfile ] file.path release ]
  Return stack: {[...] 0} {quackery 1} {[...] 8} {[...] 3} {quackery 0} {build 10} {[...] 2} {releasewords 8} {times 6} {[...] 10} {[...] 1}
```

### What is the problem
The actual problem is caused by the following:
1. `backup` puts one value on the `history` stack for every `protected` ancillary stack.
2. After backing up some stacks can become `protected`, changing the amount of `protected` stacks.
3. `bailed` takes one value from the `history` stack for every `protected` ancillary stack, which may be a different number than was put by `backup` due to new stacks being `protected`.
4. This breaks the structure of the `history` stack causing problems on one of the `bailed`.

This is particularly important because `backup` and `bailed` are run inside `build` which in turn is used to load files, so no new stack can be `protected` by executing `now!` when a file is being loaded.

### How to reproduce
Run code:
```Quackery
[ stack ] is bugged
0 backup protect bugged bailed
```

##### Expected outcome
Quackery stack contains a `0`, no problems arise.

##### Actual outcome
A problem is reported:
```Quackery
       Problem: Cannot remove an immovable item.
Quackery Stack: 
  Return stack: {[...] 0} {quackery 1} {[...] 11} {shell 5} {quackery 1} {[...] 4} {bailed 5} {[...] 6} {times 6} {[...] 10} {[...] 1}
```

### Workaround
Don't `protect` stacks inside the `backup ... bailed` construction.

This is very restrictive because it forbids `protect`ing stacks in any code that is executed at build time, especially inside files loaded with `[ $ 'filename.qky' loadfile ] now!`.

### Solution
One solution I came up with is for `backup` to store the size of the `protected` nest along with sizes of all `protected` stacks so that `bailed` doesn't need to rely on the current size of `protected` to know how many items to consume.

Another solution is that `backup` stores sizes of `protected` stacks in a nest instead of as separate values. I personally prefer this one.

### Sidenote
I think the nest of protected stacks (the first element of the `protected` stack) should include itself. If a stack is protected in a code that should be bailed out of it shouldn't keep being protected and keeping a reference to it only clutters the memory with garbage data.

Sidenote sidenote: what was the logic behind having protected items as a nest inside the `protected` stack instead of just elements of that stack?

**Comment by GordonCharlton** [comment]
Another good bug catch. Again my testing was not thorough enough. 

To address the sidenote sidenote first, I was applying the guideline that you should not need to know how many items are on a stack. `backup` needs to know how many ancillary stacks to protect, and achieves this by removing items from the nest of protected stacks until it is empty.

Now the sidenote, my instinctive reaction is that `protect protected` would probably not work, and that `protected` is a special case, which brings me to a possible solution. 

Again without thinking it through, one approach might be to include `protected share protected put` in `backup` and have `bailed` do `protected release` if `bail` has been invoked and `protected take protected release protected put` otherwise.
